name: Compile Mod on Push
on:
  push:
    branches: [ main ]
jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Compile Mod
        shell: cmd
        run: cd tools && call compile.bat

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release"
          files: |
            shared_magicbox-compiled.gsc